"""
Constants used throughout the underwriting module.
"""

BASE_CREDIT_LIMIT = 50000

LOW_RISK_THRESHOLD = 30
MEDIUM_RISK_THRESHOLD = 60
HIGH_RISK_THRESHOLD = 80

LOW_CONFIDENCE_THRESHOLD = 60
MEDIUM_CONFIDENCE_THRESHOLD = 80
HIGH_CONFIDENCE_THRESHOLD = 90

MAX_CREDIT_MULTIPLIER = 3.0
MIN_CREDIT_MULTIPLIER = 0.5

DEFAULT_TRUST_SCORE = 50
DEFAULT_REPUTATION_SCORE = 50

MAX_FRAUD_SCORE = 100