"""
Fraud Event Model

Stores raw fraud detection events generated by the governance engine.
These events are later used to generate security alerts and analytics.
"""

from datetime import datetime
from enum import Enum
import uuid

from sqlalchemy import (
    Boolean,
    DateTime,
    Enum as SQLEnum,
    Float,
    String,
)
from sqlalchemy.orm import Mapped, mapped_column

from .base import Base


# ---------------------------------------------------------------------
# ENUMS
# ---------------------------------------------------------------------

class FraudType(str, Enum):
    SUSPICIOUS_TRANSACTION = "SUSPICIOUS_TRANSACTION"
    MULTIPLE_FAILED_REQUESTS = "MULTIPLE_FAILED_REQUESTS"
    OVERSPENDING = "OVERSPENDING"
    POLICY_VIOLATION = "POLICY_VIOLATION"
    WALLET_MISUSE = "WALLET_MISUSE"
    ANOMALY = "ANOMALY"


class RiskLevel(str, Enum):
    GREEN = "GREEN"
    YELLOW = "YELLOW"
    ORANGE = "ORANGE"
    RED = "RED"
    CRITICAL = "CRITICAL"


class FraudStatus(str, Enum):
    OPEN = "OPEN"
    INVESTIGATING = "INVESTIGATING"
    RESOLVED = "RESOLVED"
    FALSE_POSITIVE = "FALSE_POSITIVE"


# ---------------------------------------------------------------------
# MODEL
# ---------------------------------------------------------------------

class FraudEvent(Base):
    """
    Represents a detected fraud or anomaly event.
    """

    __tablename__ = "fraud_events"

    # Primary Key
    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4())
    )

    # Agent Information
    agent_id: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        index=True
    )

    wallet_address: Mapped[str] = mapped_column(
        String(100),
        nullable=False
    )

    transaction_hash: Mapped[str] = mapped_column(
        String(100),
        default=""
    )

    # Fraud Information
    fraud_type: Mapped[FraudType] = mapped_column(
        SQLEnum(FraudType),
        nullable=False
    )

    risk_level: Mapped[RiskLevel] = mapped_column(
        SQLEnum(RiskLevel),
        default=RiskLevel.YELLOW
    )

    risk_score: Mapped[float] = mapped_column(
        Float,
        default=0.0
    )

    status: Mapped[FraudStatus] = mapped_column(
        SQLEnum(FraudStatus),
        default=FraudStatus.OPEN
    )

    # Detection Details
    description: Mapped[str] = mapped_column(
        String(1000),
        nullable=False
    )

    detection_source: Mapped[str] = mapped_column(
        String(100),
        nullable=False
    )

    evidence: Mapped[str] = mapped_column(
        String(2000),
        default=""
    )

    auto_blocked: Mapped[bool] = mapped_column(
        Boolean,
        default=False
    )

    # Audit
    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        onupdate=datetime.utcnow
    )