"""
Monitoring Log Model

Stores real-time monitoring events generated by the governance
module. These logs power the Mission Control dashboard,
live monitoring, analytics, and security investigations.
"""

from datetime import datetime
from enum import Enum
import uuid

from sqlalchemy import (
    DateTime,
    Enum as SQLEnum,
    Float,
    String,
)
from sqlalchemy.orm import Mapped, mapped_column

from .base import Base


# ---------------------------------------------------------------------
# ENUMS
# ---------------------------------------------------------------------

class MonitoringType(str, Enum):
    TRANSACTION = "TRANSACTION"
    WALLET = "WALLET"
    LOAN = "LOAN"
    POLICY = "POLICY"
    AGENT = "AGENT"
    SYSTEM = "SYSTEM"


class MonitoringStatus(str, Enum):
    NORMAL = "NORMAL"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


# ---------------------------------------------------------------------
# MODEL
# ---------------------------------------------------------------------

class MonitoringLog(Base):
    """
    Stores live monitoring events for governance services.
    """

    __tablename__ = "monitoring_logs"

    # Primary Key
    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4())
    )

    # Related Agent
    agent_id: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        index=True
    )

    # Event Information
    monitoring_type: Mapped[MonitoringType] = mapped_column(
        SQLEnum(MonitoringType),
        nullable=False
    )

    status: Mapped[MonitoringStatus] = mapped_column(
        SQLEnum(MonitoringStatus),
        default=MonitoringStatus.NORMAL
    )

    event_name: Mapped[str] = mapped_column(
        String(200),
        nullable=False
    )

    description: Mapped[str] = mapped_column(
        String(1000),
        nullable=False
    )

    source: Mapped[str] = mapped_column(
        String(100),
        nullable=False
    )

    reference_id: Mapped[str] = mapped_column(
        String(100),
        default=""
    )

    risk_score: Mapped[float] = mapped_column(
        Float,
        default=0.0
    )

    event_metadata: Mapped[str] = mapped_column(
    String(2000),
    default=""
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow
    )