"""
Security Alert Model

Stores all governance and security alerts generated by the
monitoring engine, fraud detector and policy engine.
"""

from datetime import datetime
from enum import Enum
import uuid

from sqlalchemy import (
    Boolean,
    DateTime,
    Enum as SQLEnum,
    String,
)
from sqlalchemy.orm import Mapped, mapped_column

from .base import Base


# ---------------------------------------------------------------------
# ENUMS
# ---------------------------------------------------------------------

class AlertType(str, Enum):
    FRAUD = "FRAUD"
    POLICY = "POLICY"
    SPENDING = "SPENDING"
    WALLET = "WALLET"
    RISK = "RISK"
    SYSTEM = "SYSTEM"


class AlertSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AlertStatus(str, Enum):
    ACTIVE = "ACTIVE"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"


# ---------------------------------------------------------------------
# MODEL
# ---------------------------------------------------------------------

class SecurityAlert(Base):
    """
    Stores explainable security alerts generated by governance services.
    """

    __tablename__ = "security_alerts"

    # Primary Key
    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4())
    )

    # Related Agent
    agent_id: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        index=True
    )

    # Alert Classification
    alert_type: Mapped[AlertType] = mapped_column(
        SQLEnum(AlertType),
        nullable=False
    )

    severity: Mapped[AlertSeverity] = mapped_column(
        SQLEnum(AlertSeverity),
        default=AlertSeverity.MEDIUM
    )

    status: Mapped[AlertStatus] = mapped_column(
        SQLEnum(AlertStatus),
        default=AlertStatus.ACTIVE
    )

    # Explainable Alert Information
    title: Mapped[str] = mapped_column(
        String(200),
        nullable=False
    )

    description: Mapped[str] = mapped_column(
        String(1000),
        nullable=False
    )

    reason: Mapped[str] = mapped_column(
        String(1000),
        nullable=False
    )

    suggested_action: Mapped[str] = mapped_column(
        String(1000),
        nullable=False
    )

    impact: Mapped[str] = mapped_column(
        String(1000),
        nullable=False
    )

    # Resolution
    is_resolved: Mapped[bool] = mapped_column(
        Boolean,
        default=False
    )

    resolved_by: Mapped[str] = mapped_column(
        String(100),
        default=""
    )

    # Audit
    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        onupdate=datetime.utcnow
    )