from __future__ import annotations

from decimal import Decimal

# Core financial defaults
CURRENCY = "USD"
ZERO_AMOUNT = Decimal("0.00")
MIN_AMOUNT = Decimal("0.01")
MAX_ESCROW_RELEASE_PERCENT = Decimal("100.00")
DEFAULT_INTEREST_RATE = Decimal("0.00")
AUTO_REPAYMENT_FALLBACK_LIMIT = Decimal("0.00")

# Common status values used across wallet, repayment, escrow, revenue, and transactions
PAYMENT_STATUS_PENDING = "pending"
PAYMENT_STATUS_PROCESSING = "processing"
PAYMENT_STATUS_COMPLETED = "completed"
PAYMENT_STATUS_FAILED = "failed"
PAYMENT_STATUS_OVERDUE = "overdue"

ESCROW_STATUS_PENDING = "pending"
ESCROW_STATUS_ACTIVE = "active"
ESCROW_STATUS_LOCKED = "locked"
ESCROW_STATUS_RELEASED = "released"
ESCROW_STATUS_CANCELLED = "cancelled"
ESCROW_STATUS_FAILED = "failed"

REVENUE_STATUS_PENDING = "pending"
REVENUE_STATUS_EARNED = "earned"
REVENUE_STATUS_DECLINED = "declined"

TRANSACTION_TYPE_CREDIT = "credit"
TRANSACTION_TYPE_DEBIT = "debit"
TRANSACTION_TYPE_REPAYMENT = "repayment"
TRANSACTION_TYPE_ESCROW_LOCK = "escrow_lock"
TRANSACTION_TYPE_ESCROW_RELEASE = "escrow_release"
TRANSACTION_TYPE_REVENUE = "revenue"

REPAYMENT_MODE_WALLET = "wallet"
REPAYMENT_MODE_ESCROW = "escrow"
REPAYMENT_MODE_DIRECT = "direct"

REPAYMENT_TYPE_AUTOMATIC = "automatic"
REPAYMENT_TYPE_PARTIAL = "partial"
REPAYMENT_TYPE_MILESTONE = "milestone"
REPAYMENT_TYPE_MANUAL = "manual"

ESCROW_TRIGGER_TASK_START = "task_start"
ESCROW_TRIGGER_MILESTONE_REACHED = "milestone_reached"
ESCROW_TRIGGER_TASK_COMPLETED = "task_completed"
ESCROW_TRIGGER_MANUAL = "manual"

# Safety / business rules
MIN_BALANCE_REQUIRED_FOR_ESCROW = Decimal("0.00")
MAX_REPAYMENT_RATIO = Decimal("1.00")
REVENUE_DELAY_DAYS_LIMIT = 30

__all__ = [
    "CURRENCY",
    "ZERO_AMOUNT",
    "MIN_AMOUNT",
    "MAX_ESCROW_RELEASE_PERCENT",
    "DEFAULT_INTEREST_RATE",
    "AUTO_REPAYMENT_FALLBACK_LIMIT",
    "PAYMENT_STATUS_PENDING",
    "PAYMENT_STATUS_PROCESSING",
    "PAYMENT_STATUS_COMPLETED",
    "PAYMENT_STATUS_FAILED",
    "PAYMENT_STATUS_OVERDUE",
    "ESCROW_STATUS_PENDING",
    "ESCROW_STATUS_ACTIVE",
    "ESCROW_STATUS_LOCKED",
    "ESCROW_STATUS_RELEASED",
    "ESCROW_STATUS_CANCELLED",
    "ESCROW_STATUS_FAILED",
    "REVENUE_STATUS_PENDING",
    "REVENUE_STATUS_EARNED",
    "REVENUE_STATUS_DECLINED",
    "TRANSACTION_TYPE_CREDIT",
    "TRANSACTION_TYPE_DEBIT",
    "TRANSACTION_TYPE_REPAYMENT",
    "TRANSACTION_TYPE_ESCROW_LOCK",
    "TRANSACTION_TYPE_ESCROW_RELEASE",
    "TRANSACTION_TYPE_REVENUE",
    "REPAYMENT_MODE_WALLET",
    "REPAYMENT_MODE_ESCROW",
    "REPAYMENT_MODE_DIRECT",
    "REPAYMENT_TYPE_AUTOMATIC",
    "REPAYMENT_TYPE_PARTIAL",
    "REPAYMENT_TYPE_MILESTONE",
    "REPAYMENT_TYPE_MANUAL",
    "ESCROW_TRIGGER_TASK_START",
    "ESCROW_TRIGGER_MILESTONE_REACHED",
    "ESCROW_TRIGGER_TASK_COMPLETED",
    "ESCROW_TRIGGER_MANUAL",
    "MIN_BALANCE_REQUIRED_FOR_ESCROW",
    "MAX_REPAYMENT_RATIO",
    "REVENUE_DELAY_DAYS_LIMIT",
]
